### ISSUE TITLE
Implement upload to openbuildprop

### ISSUE THREAD

**Issue by dalb8** [nathanpc/Build.prop-Editor#1]
https://github.com/0xD34D/OpenBuildProp http://openbuildprop.scheffsblend.com/

**Comment by nathanpc** [comment]
Interesting idea. I'll add this to the TODO list and it might get into the 2.1 update if the developer (@0xD34D) let's me use it, since he didn't specified the license it's using for his project.

Thanks very much for the feedback.

**Comment by 0xD34D** [comment]
I have no problem with build.prop files being submitted from other applications.  More is better. The only thing I would be concerned with is modified versions being submitted.  If there is a way to prompt the user on first run if they would like to contribute their original build.prop then this may be less of an issue.  There is always the possibility of modified build.prop files being submitted but if that possibility can be mitigated then that would be ideal.

**Comment by nathanpc** [comment]
@0xD34D I can make a dialog pop when the user runs the application for the first time asking if they want to submit their build.prop file and warning that it should be a unmodified one.

**Comment by 0xD34D** [comment]
That would be great.  Perhaps you could use a boolean shared preference for keeping track if they modify it as a safety catch from uploading a modified build.prop.  Unless there is no way to upload after the user declines initially.  In which case there would probably be no need for such a safety.

**Comment by dalb8** [comment]
On the other hand , maybe it's not such a good idea to include the Internet permission.

**Comment by f1vefour** [comment]
I agree, no need to add Internet permissions.
