### ISSUE TITLE
Edit not working on Cm nightly

### ISSUE THREAD

**Issue by dalb8** [nathanpc/Build.prop-Editor#2]
I'm using Cm nightly 0411 on p990. When I edit a field it and press OK the original value remains. Sometimes, later, the change does register.

**Comment by nathanpc** [comment]
Could you please provide the logcat output when you're running the app?

**Comment by dalb8** [comment]
It seems that when the app restarts the changed value is displayed

**Comment by nathanpc** [comment]
Ahh, this is a know bug that the app doesn't refresh the list after the user makes a change to the file, then when the user restarts the app will read the entire file again, so the list will show the edited fields correctly.

This is already on my TODO list since the release of version 2.0
